// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using UrbanInfraSystem.Infrastructure.Persistence;

#nullable disable

namespace UrbanInfraSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818074720_UpdateIssueAndSlaSchema")]
    partial class UpdateIssueAndSlaSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geography");

                    b.Property<decimal?>("CentroidLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("CentroidLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentAreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AreaId");

                    b.HasIndex("ParentAreaId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AuditLogs_OccurredAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.DepartmentMember", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("DepartmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DepartmentMembers", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.EscalationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EscalationRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscalationRuleId");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("IX_EscalationEvents_IssueId");

                    b.HasIndex("TargetDepartmentId")
                        .HasDatabaseName("IX_EscalationEvents_TargetDepartmentId");

                    b.ToTable("EscalationEvents", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.EscalationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NotificationTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OverdueMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("SlaPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("TargetRoleName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TargetDepartmentId");

                    b.HasIndex("SlaPolicyId", "EscalationLevel", "OverdueMinutes", "TargetDepartmentId", "TargetRoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_EscalationRules_UniqueCombination")
                        .HasFilter("[TargetDepartmentId] IS NOT NULL AND [TargetRoleName] IS NOT NULL");

                    b.ToTable("EscalationRules", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Issue", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IssueId"));

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CustomTypeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DuplicateOfIssueId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("IssueTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("AreaId");

                    b.HasIndex("IssueTypeId");

                    b.HasIndex("Latitude")
                        .HasDatabaseName("IX_Issues_Latitude");

                    b.HasIndex("Longitude")
                        .HasDatabaseName("IX_Issues_Longitude");

                    b.HasIndex("PriorityId");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Issues_PublicCode");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_Issues_ReportId");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("IX_Issues_ReportedAt");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("IX_Issues_ReporterId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_Issues_StatusId");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("AssignmentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AssignmentNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RoutingRuleId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoutingRuleId");

                    b.HasIndex("IssueId", "IsCurrent");

                    b.ToTable("IssueAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_IssueAssignments_Method", "AssignmentMethod IN ('AUTO', 'MANUAL', 'TRANSFER', 'ESCALATION')");
                        });
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAssignmentMember", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MemberId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("AssignmentId", "UserId")
                        .IsUnique();

                    b.ToTable("IssueAssignmentMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_IssueAssignmentMembers_Status", "Status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("UpdateId")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("IX_IssueAttachments_IssueId");

                    b.HasIndex("UpdateId")
                        .HasDatabaseName("IX_IssueAttachments_UpdateId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("IssueAttachments", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssuePriority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PriorityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("SeverityRank")
                        .HasColumnType("tinyint");

                    b.HasKey("PriorityId");

                    b.HasIndex("PriorityCode")
                        .IsUnique();

                    b.HasIndex("SeverityRank")
                        .IsUnique();

                    b.ToTable("IssuePriorities", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueSla", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FirstRespondedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FirstResponseDueAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("FirstResponseMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstResponseBreached")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolutionBreached")
                        .HasColumnType("bit");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ResolutionDueAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasDatabaseName("IX_IssueSlas_IssueId");

                    b.HasIndex("SlaPolicyId");

                    b.ToTable("IssueSlas", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublicVisible")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("StatusId");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("IssueStatuses", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueType", b =>
                {
                    b.Property<int>("IssueTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueTypeId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentIssueTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IssueTypeId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_IssueTypes_IsActive");

                    b.HasIndex("ParentIssueTypeId")
                        .HasDatabaseName("IX_IssueTypes_ParentIssueTypeId");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_IssueTypes_TypeCode");

                    b.ToTable("IssueTypes", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte?>("ProgressPercent")
                        .HasColumnType("tinyint");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_IssueUpdates_CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("IX_IssueUpdates_IssueId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("IssueUpdates", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueUpvote", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("IssueId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_IssueUpvotes_UserId");

                    b.ToTable("IssueUpvotes", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long?>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("AreaId");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.HasIndex("ReportedAt");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.ReportUpvote", b =>
                {
                    b.Property<long>("ReportId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ReportId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportUpvotes", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.RoutingRule", b =>
                {
                    b.Property<int>("RoutingRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoutingRuleId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("RoutingRuleId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IssueTypeId");

                    b.HasIndex("AreaId", "IssueTypeId")
                        .IsUnique();

                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstResponseMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IssueTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("IssueTypeId", "PriorityId")
                        .IsUnique();

                    b.ToTable("SlaPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_SlaPolicies_Minutes_Positive", "ResolutionMinutes > 0 AND FirstResponseMinutes > 0");
                        });
                });

            modelBuilder.Entity("UrbanInfraSystem.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Area", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Area", "ParentArea")
                        .WithMany("SubAreas")
                        .HasForeignKey("ParentAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentArea");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Department", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.DepartmentMember", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.EscalationEvent", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.EscalationRule", "EscalationRule")
                        .WithMany()
                        .HasForeignKey("EscalationRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EscalationRule");

                    b.Navigation("Issue");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.EscalationRule", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.SlaPolicy", "SlaPolicy")
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SlaPolicy");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Issue", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssuePriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Report", "Report")
                        .WithMany("Issues")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("IssueType");

                    b.Navigation("Priority");

                    b.Navigation("Report");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAssignment", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithMany("Assignments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.RoutingRule", "RoutingRule")
                        .WithMany()
                        .HasForeignKey("RoutingRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Issue");

                    b.Navigation("RoutingRule");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAssignmentMember", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueAssignment", "Assignment")
                        .WithMany("Members")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAttachment", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithMany("Attachments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueUpdate", "Update")
                        .WithMany("Attachments")
                        .HasForeignKey("UpdateId");

                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Update");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueSla", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithOne("Sla")
                        .HasForeignKey("UrbanInfraSystem.Domain.Entities.IssueSla", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.SlaPolicy", "SlaPolicy")
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("SlaPolicy");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueType", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueType", "ParentIssueType")
                        .WithMany("SubIssueTypes")
                        .HasForeignKey("ParentIssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentIssueType");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueUpdate", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithMany("Updates")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("Issue");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueUpvote", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Issue", "Issue")
                        .WithMany("Upvotes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Report", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.ReportUpvote", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Report", "Report")
                        .WithMany("Upvotes")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.RoutingRule", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Department");

                    b.Navigation("IssueType");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.SlaPolicy", b =>
                {
                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssueType", "IssueType")
                        .WithMany("SlaPolicies")
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanInfraSystem.Domain.Entities.IssuePriority", "IssuePriority")
                        .WithMany("SlaPolicies")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssuePriority");

                    b.Navigation("IssueType");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Area", b =>
                {
                    b.Navigation("SubAreas");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("Sla");

                    b.Navigation("Updates");

                    b.Navigation("Upvotes");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueAssignment", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssuePriority", b =>
                {
                    b.Navigation("SlaPolicies");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueType", b =>
                {
                    b.Navigation("SlaPolicies");

                    b.Navigation("SubIssueTypes");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.IssueUpdate", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("UrbanInfraSystem.Domain.Entities.Report", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Upvotes");
                });

            modelBuilder.Entity("UrbanInfraSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
